=== RootKoro/hintsL3GLSI/XML/bulletins.dtd
<!ELEMENT faculte (etudiant+)>
<!ELEMENT etudiant (nom , prenom , modules)>
<!ATTLIST etudiant id CDATA #REQUIRED>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT modules (nom_module+)>
<!ELEMENT nom_module (#PCDATA)>
<!ATTLIST nom_module note CDATA #REQUIRED>

=== RootKoro/hintsL3GLSI/XML/bulletins.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE bulletins SYSTEM "bulletins.dtd">
<faculte>
  <etudiant id="1">
    <nom>MARONE</nom>
    <prenom>ASTOU</prenom>
    <modules>
      <nom_module note=" 13">oracle</nom_module>
      <nom_module note=" 19">programmation</nom_module>
       <nom_module note="14 ">reseau</nom_module>
    </modules>
  </etudiant>

  <etudiant id="2">
    <nom>NDIAYE</nom>
    <prenom>DABA</prenom>
    <modules>
      <nom_module note="15"> oracle </nom_module>
      <nom_module note="11"> programmation </nom_module>
      <nom_module note="13"> reseau </nom_module>
    </modules>
  </etudiant>
</faculte>
