<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE regions [
<!ELEMENT regions (region)+>
<!ELEMENT region (name)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST region id CDATA #REQUIRED>
]>
<regions>
  <region id="1">
	   <name>Europe</name>
  </region>
   <region id="2">
	<name>Americas</name>
  </region>
   <region id="3">
	<name>Asia</name>
  </region>
   <region id="4">
	<name>Middle East and Africa</name>
  </region>
</regions>
